version: "3.1"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: main
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
